version: '3.8'

services:
  api:
    build: ./main-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=5432
      - PORT=8080
      - CSV_PATH=/app/data/notes.csv
      - EXTERNAL_API_URL=http://external_api:8081/data
      - TICK_FREQUENCY=50
    volumes:
      - ./data:/app/data
    networks:
      - api-network
    depends_on:
      - data-generator
      - db
      - external_api
  
  external_api:
    build: ./external-api
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - api-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network

  data-generator:
    build: ./data-generator
    volumes:
      - ./data:/app/data

networks:
  api-network:
    driver: bridge

volumes:
  postgres_data:

